Add the missing exports condition to support vite-plugin-svelte v3
romkor/svelte-portal pull request #178
Opened 2023-12-20 15:41 UTC by harshmandan

Fixes #177

2024-01-15 23:45 UTC, ebeloded commented
Can this be merged please, @romkor?

2024-01-16 09:22 UTC, romkor requested changes

2024-01-16 09:22 UTC, romkor commented on package.json
> +      "svelte": "src/main.es.js"
```suggestion
    ".": {
      "types": "./src/Portal.svelte.d.ts",
      "svelte": "src/main.es.js"
    }
```
Please add closing brace

2024-01-16 09:22 UTC, romkor commented on package.json
> +  "version": "2.2.1",
```suggestion
  "version": "2.2.0",
```
Version will be bumped automatically

2024-01-16 17:51 UTC, merged

2024-01-17 09:09 UTC, romkor commented
@harshmandan just released